sudo: required

language: python
python:
  - "2.7"
  - "2.6"

os: 
  - ubuntu
  - centos
  
cache: pip
install: "pip install -r requirements.txt"
  
script:
  - python test.py
  
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "jbudzynski9"
      - git config --local user.email "jbudzynski95@gmail.com"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
  
deploy:
  provider: releases
  api_key: "9eb4f8e17ffcbb28be3c7de0a767355e605ee84e"
  file: test.py
  skip_cleanup: true
  on:
    repo: jbudzynski9/travis-test
    tags: true
