language: python

python:
  - "2.7"
  - "2.6"

os: 
  - ubuntu
  - centos
  
cache: pip
install: "pip install -r requirements.txt"
  
script:
  - python test.py
  
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "jbudzynski9"
      - git config --local user.email "jbudzynski95@gmail.com"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag -a $TRAVIS_TAG -m "new tag - $TRAVIS_TAG"
  
deploy:
  provider: releases
  api_key: "$travis"
  file: test.py
  skip_cleanup: true
  on:
    tags: false
